version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookstore
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

volumes:
  mongo-data:
